CREATE DATABASE notes_app;

CREATE TABLE users(
  id SERIAL PRIMARY KEY,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(100)
);

CREATE TABLE notes(
  id SERIAL PRIMARY KEY,
  title VARCHAR(255),
  content VARCHAR(500)
);
